import "./globals.css";
import Navbar from "../components/Navbar";
import { ClientOnlyProvider } from "../components/ClientOnlyProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body className="bg-white text-black">
        <Navbar />
        <ClientOnlyProvider>{children}</ClientOnlyProvider>
      </body>
    </html>
  );
}
